spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentACar
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  main:
    banner-mode: off
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    root: warn